os: linux
services: docker

env:
  global:
    - PROJECT_NAME: SOOS_DAST_TravisCI_Example
    - SCAN_MODE: baseline
    - TARGET_URL: https://api.soos.io/api/

script:
  - docker run soosio/dast
                    --clientId=SOOS_CLIENT_ID
                    --apiKey=SOOS_API_KEY 
                    --projectName=SOOS_DAST_TravisCI_Example
                    --scanMode=baseline
                    https://api.soos.io/api/