version: '2.1'
orbs:
  soos: soos-io/sca@X.Y.Z
workflows:
  main:
    jobs:
      - soos/analysis_async_init:
          client_id: <<SOOS Client Id>>
          api_key: <<SOOS API Key>>
      - soos/analysis_async_result:
          client_id: <<SOOS Client Id>>
          api_key: <<SOOS API Key>>
          requires:
            - soos/analysis_async_init
          project_name: "selene-circleci-sca"