
version: 2.1

orbs:
  soos: soos-io/sca@x.y.z # Get the latest version at https://circleci.com/developer/orbs/orb/soos-io/sca

workflows:
  main:
    jobs:
      - soos/analysis_run_and_wait:
          client_id: ${SOOS_CLIENT_ID}
          api_key: ${SOOS_API_KEY}
          project_name: "selene-circleci-sca"